spring.datasource.url: jdbc:mysql://localhost:3306/trafficSchool?useSSL=false&useUnicode=true&CharSet=utf-8&connectionCollation=utf8_general_ci&characterSetResults=utf8&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username: trafficSchool
spring.datasource.password: trafficSchoolZebra2019*
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
hibernate.dialect: org.hibernate.dialect.MySQL5DBDialect
spring.jpa.show-sql: "true"
spring.jpa.hibernate.ddl-auto: create-drop
admin.embg: admin
admin.firstName: Благој
admin.lastName: Благојовски
admin.email: zebra@yahoo.com
admin.password: nimda
admin.role: ADMIN